micronaut:
  application:
    name: Kaatarina
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    url: REPLACE_WITH_ACTUAL_URL
    username: REPLACE_WITH_ACTUAL_USERNAME
    password: REPLACE_WITH_ACTUAL_PASSWORD